//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbotutU
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Fb { get; set; }
        public string Twitter { get; set; }
        public string Instgram { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    }
}
